### ISSUE TITLE
node app crashes when updating active sprint

### ISSUE THREAD

**Issue by ghost** [devtyr/trello-burndown#18]
Hi here is what happens when i try to update an active sprint. (where XXX is the board id or the list id)

[STATUS] RestClient request send, URL: https://api.trello.com/1/boards/XXX/lists
[STATUS] RestClient request send, Method: GET
[STATUS] RestClient request send, URL: https://api.trello.com/1/lists/XXX/cards
[STATUS] RestClient request send, Method: GET
[STATUS] RestClient request send, URL: https://api.trello.com/1/lists/XXX/cards
[STATUS] RestClient request send, Method: GET
[STATUS] RestClient request send, URL: https://api.trello.com/1/lists/XXX/cards
[STATUS] RestClient request send, Method: GET

TypeError: Cannot read property 'length' of null
    at CardStatistics.generate (/Path/To/TrelloBurndown/trello-burndown/lib/cardstatistics.js:36:14)
    at /Path/To/TrelloBurndown/trello-burndown/lib/helper.js:90:15
    at /Path/To/TrelloBurndown/trello-burndown/lib/cardreceiver.js:64:9
    at /Path/To/TrelloBurndown/trello-burndown/node_modules/trello_ex/main.js:20:13
    at Request._callback (/Path/To/TrelloBurndown/trello-burndown/node_modules/trello_ex/node_modules/rest-client/lib/index.js:67:9)
    at Request.self.callback (/Path/To/TrelloBurndown/trello-burndown/node_modules/trello_ex/node_modules/rest-client/node_modules/request/index.js:148:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/Path/To/TrelloBurndown/trello-burndown/node_modules/trello_ex/node_modules/rest-client/node_modules/request/index.js:886:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Path/To/TrelloBurndown/trello-burndown/node_modules/trello_ex/node_modules/rest-client/node_modules/request/index.js:837:12)

**Comment by chase-seibert** [comment]
I'm having the same issue.

**Comment by devtyr** [comment]
Do you have the latest bits here from GitHub or via NPM installed?

**Comment by chase-seibert** [comment]
I'm running 0.9. I'll try the latest.

**Comment by chase-seibert** [comment]
Yep, it works on 1.0.0.

**Comment by devtyr** [comment]
Does this also work for @ronjawilkening ?

**Comment by ghost** [comment]
Yes. Latest version works.
