### ISSUE TITLE
Board ID not defined

### ISSUE THREAD

**Issue by bjornandersson** [devtyr/trello-burndown#28]
When I run generate.js I get this error:

Starting export ...

/home/adminuser/websites/trello-burndown/node_modules/trello-burndown/lib/cardreceiver.js:20
                throw new Error(errors.MISSING_BOARD_ID);
                      ^
Error: Board ID not defined
    at new CardReceiver (/home/adminuser/websites/trello-burndown/node_modules/trello-burndown/lib/cardreceiver.js:20:9)
    at Helper.generateAndExport (/home/adminuser/websites/trello-burndown/node_modules/trello-burndown/lib/helper.js:92:17)
    at Object.<anonymous> (/home/adminuser/websites/trello-burndown/node_modules/trello-burndown/generate.js:86:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

I found the board id by using info.js and have set it in settings.json.

**Comment by devtyr** [comment]
There was a fix. Get the latest bits and please try again.

**Comment by jdhurst** [comment]
I'm getting the same error on 0.9.2.

**Comment by FuriousCoder74** [comment]
I was failing to run info.js, and was just using the board title, not the numeric ID. Using the latter fixed this.
